/**
 * Generated by bf-cmp
 */

#include <stdlib.h>

extern void bf_init();
extern char bf_end();
extern void bf_ptr_inc_n(size_t);
extern void bf_ptr_dec_n(size_t);
extern void bf_inc_arr(size_t);
extern char bf_dec_arr(size_t);
extern void bf_in();
extern void bf_out_n(size_t);
extern char bf_get();

void example(void)
{
	bf_ptr_inc_n(3);
	bf_inc_arr(2);
	bf_ptr_dec_n(3);
}

void another(void)
{
	bf_inc_arr(6);
}

int main(void)
{
	bf_init();
	bf_inc_arr(1);
	return bf_end();
}

